let mongoose=require('mongoose');
let Schema=mongoose.Schema;
leavesSchema=new Schems({
    employeeId:{
        type:mongoose.Schema.Types.OblectId,
        ref:'User',
        required:true
    },
    leaveType:{
        type:String,
        Enum:['casual','sick','paid'],
        required:true
    },
    startDate:{
        type:Date,
        required:true
    },
    endDate:{
        type:String,
        required:true,
        reason:{
            type:String
        },
        status:{
            type:String,
            Enum:['pending','approved','rejected'],
            default:'pending'
        },
        appliedAt:{
            type:Date,
            default:Date.now
        },
        reviewedBy:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'User'
        },
    },
});
module.exports=mongoose.model(leavesSchema);